Add keytab section

diff --git a/run_spark b/run_spark
--- a/run_spark
+++ b/run_spark
@@ -1,8 +1,19 @@
 #!/bin/sh
 # Author: Valentin Kuznetsov <vkuznet AT gmail [DOT] com>
-# A wrapper script to submit spark job with CMSSpark python script.
+# A wrapper script to submit spark job with python script.
 
-# on vocms092 spark-submit resides in non-standard location
+# Kerberos
+keytab=/etc/secrets/keytab
+principal=`klist -k "$keytab" | tail -1 | awk '{print $2}'`
+echo "principal=$principal"
+kinit $principal -k -t "$keytab"
+if [ $? == 1 ]; then
+    echo "Unable to perform kinit"
+    exit 1
+fi
+klist -k "$keytab"
+
+# add non-standard location of hadoop
 export PATH=$PATH:/usr/hdp/spark/bin
 
 # test arguments
