Remove spark-examples jars and make keytab check optional

diff --git a/run_spark b/run_spark
--- a/run_spark
+++ b/run_spark
@@ -4,14 +4,16 @@
 
 # Kerberos
 keytab=/etc/secrets/keytab
-principal=`klist -k "$keytab" | tail -1 | awk '{print $2}'`
-echo "principal=$principal"
-kinit $principal -k -t "$keytab"
-if [ $? == 1 ]; then
-    echo "Unable to perform kinit"
-    exit 1
+if [ -f $keytab ]; then
+    principal=`klist -k "$keytab" | tail -1 | awk '{print $2}'`
+    echo "principal=$principal"
+    kinit $principal -k -t "$keytab"
+    if [ $? == 1 ]; then
+        echo "Unable to perform kinit"
+        exit 1
+    fi
+    klist -k "$keytab"
 fi
-klist -k "$keytab"
 
 # add non-standard location of hadoop
 export PATH=$PATH:/usr/hdp/spark/bin
@@ -69,30 +71,11 @@ fi
 spark2=`spark-submit --version 2>&1 | grep "version 2"`
 if [ -n "$spark2" ] || [ -f $lxplus7_spark ]; then
     echo "Using spark 2.X"
-    sparkexjar=`ls /usr/hdp/spark/jars/spark-examples* /usr/hdp/spark-2/examples/jars/spark-examples* 2> /dev/null | tail -1`
-    if [ -n "$sparkexjar" ]; then
-        jars="$sparkexjar"
-    else
-        jars="/afs/cern.ch/user/v/valya/public/spark/spark-examples-1.6.0-cdh5.15.1-hadoop2.6.0-cdh5.15.1.jar"
-    fi
+    jars=""
     conf="$conf --packages com.databricks:spark-avro_2.11:4.0.0"
 else
     echo "Using spark 1.X"
-    csvjar=/afs/cern.ch/user/v/valya/public/spark/spark-csv-assembly-1.4.0.jar
-    avrojar=/afs/cern.ch/user/v/valya/public/spark/avro-mapred-1.7.6-cdh5.7.6.jar
-    jars="$csvjar,$avrojar"
-    if [ -f /usr/hdp/spark-2/examples/jars/spark-examples_2.11-2.3.2.jar ]; then
-        sparkexjar=/usr/hdp/spark-2/examples/jars/spark-examples_2.11-2.3.2.jar
-        jars="$jars,$sparkexjar"
-    else
-        sparkexjar=`ls /usr/lib/spark/examples/lib/spark-examples* 2> /dev/null | tail -1`
-        if [ -n "$sparkexjar" ]; then
-            jars="$jars,$sparkexjar"
-        else
-            sparkexjar=/afs/cern.ch/user/v/valya/public/spark/spark-examples-1.6.0-cdh5.15.1-hadoop2.6.0-cdh5.15.1.jar
-            jars="$jars,$sparkexjar"
-        fi
-    fi
+    jars=""
     mapreduce=/eos/project/s/swan/public/hadoop-mapreduce-client-core-2.6.0-cdh5.7.6.jar
     if [ ! -f $mapreduce ]; then
         mapreduce=/usr/lib/hadoop-mapreduce/hadoop-mapreduce-client-core-2.6.0-cdh5.7.6.jar
